#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v2
# autospec commit: 250a666
#
Name     : QAT-ZSTD-Plugin
Version  : 0.1.0
Release  : 1
URL      : https://github.com/intel/QAT-ZSTD-Plugin/archive/refs/tags/v0.1.0.tar.gz
Source0  : https://github.com/intel/QAT-ZSTD-Plugin/archive/refs/tags/v0.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: QAT-ZSTD-Plugin-license = %{version}-%{release}
BuildRequires : qatlib-dev
BuildRequires : zstd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: prefix.patch

%description
# Intel&reg; QuickAssist Technology ZSTD Plugin (QAT ZSTD Plugin)
## Table of Contents

%package dev
Summary: dev components for the QAT-ZSTD-Plugin package.
Group: Development
Provides: QAT-ZSTD-Plugin-devel = %{version}-%{release}
Requires: QAT-ZSTD-Plugin = %{version}-%{release}

%description dev
dev components for the QAT-ZSTD-Plugin package.


%package license
Summary: license components for the QAT-ZSTD-Plugin package.
Group: Default

%description license
license components for the QAT-ZSTD-Plugin package.


%prep
%setup -q -n QAT-ZSTD-Plugin-0.1.0
cd %{_builddir}/QAT-ZSTD-Plugin-0.1.0
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1698245594
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
make  %{?_smp_mflags}  PREFIX=%{buildroot}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1698245594
rm -rf %{buildroot}
## install_prepend content
mkdir -p %{buildroot}/usr/lib64
## install_prepend end
mkdir -p %{buildroot}/usr/share/package-licenses/QAT-ZSTD-Plugin
cp %{_builddir}/QAT-ZSTD-Plugin-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/QAT-ZSTD-Plugin/86f5b7fd53ceeabe1645051a6bb84415e1fdaeef || :
cp %{_builddir}/QAT-ZSTD-Plugin-%{version}/LICENSE.ZSTD %{buildroot}/usr/share/package-licenses/QAT-ZSTD-Plugin/d5e630eee1d3500039f2e16bed21d0f0cd580994 || :
%make_install
## install_append content
INSTALLDIR=/usr
## install_append end

%files
%defattr(-,root,root,-)
/usr/include

%files dev
%defattr(-,root,root,-)
/usr/lib64/libqatseqprod.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/QAT-ZSTD-Plugin/86f5b7fd53ceeabe1645051a6bb84415e1fdaeef
/usr/share/package-licenses/QAT-ZSTD-Plugin/d5e630eee1d3500039f2e16bed21d0f0cd580994
